/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg;

/**
 *
 * @author Carlos
 */


public class NewJFrame extends javax.swing.JFrame {

      int int_vidadr = 4000;
      int int_vidacaballero = 2500;
      int int_vidaslime = 3000;
      int int_vidag = 3500;
      int b = (int)Math.floor(Math.random()*4);
      int c = 0;
      int a = 0;
      
      
      
    /*
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AtackSlime = new javax.swing.JButton();
        AttackD = new javax.swing.JButton();
        BarravidaSlime = new javax.swing.JProgressBar();
        Barravidad = new javax.swing.JProgressBar();
        attackCaballero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vidacaballero = new javax.swing.JProgressBar();
        Ataquecargado = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        Curar = new javax.swing.JButton();
        Curard = new javax.swing.JButton();
        AtaqueG = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 11, 0, 362);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 258, 0, 433);

        AtackSlime.setText("Atacar");
        AtackSlime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtackSlimeMousePressed(evt);
            }
        });
        AtackSlime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtackSlimeActionPerformed(evt);
            }
        });
        getContentPane().add(AtackSlime);
        AtackSlime.setBounds(720, 880, 65, 23);

        AttackD.setText("Atacar");
        AttackD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackDActionPerformed(evt);
            }
        });
        getContentPane().add(AttackD);
        AttackD.setBounds(1110, 730, 65, 23);

        BarravidaSlime.setMaximum(3000);
        BarravidaSlime.setValue(3000);
        getContentPane().add(BarravidaSlime);
        BarravidaSlime.setBounds(620, 860, 146, 14);

        Barravidad.setMaximum(4000);
        Barravidad.setValue(4000);
        getContentPane().add(Barravidad);
        Barravidad.setBounds(1110, 710, 146, 14);

        attackCaballero.setText("Atacar");
        attackCaballero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attackCaballeroMousePressed(evt);
            }
        });
        attackCaballero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackCaballeroActionPerformed(evt);
            }
        });
        getContentPane().add(attackCaballero);
        attackCaballero.setBounds(690, 620, 65, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\RPG\\g10079.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 700, 206, 151);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\RPG\\PieceDragonbltG.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(950, 310, 400, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\RPG\\caballero.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 70, 503, 527);

        vidacaballero.setMaximum(2500);
        vidacaballero.setToolTipText("");
        vidacaballero.setValue(2500);
        getContentPane().add(vidacaballero);
        vidacaballero.setBounds(610, 600, 146, 14);

        Ataquecargado.setText("Ataque Cargado");
        Ataquecargado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtaquecargadoMousePressed(evt);
            }
        });
        Ataquecargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaquecargadoActionPerformed(evt);
            }
        });
        getContentPane().add(Ataquecargado);
        Ataquecargado.setBounds(600, 880, 111, 23);

        jProgressBar1.setMaximum(3500);
        jProgressBar1.setValue(3500);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(190, 700, 146, 14);

        Curar.setText("Curar");
        Curar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CurarMousePressed(evt);
            }
        });
        getContentPane().add(Curar);
        Curar.setBounds(620, 620, 59, 23);

        Curard.setText("Curar");
        Curard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CurardMousePressed(evt);
            }
        });
        getContentPane().add(Curard);
        Curard.setBounds(1190, 730, 59, 23);

        AtaqueG.setText("Ataque");
        AtaqueG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtaqueGMousePressed(evt);
            }
        });
        getContentPane().add(AtaqueG);
        AtaqueG.setBounds(280, 720, 67, 20);

        jButton2.setText("Bloqueo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 720, 71, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/g12777.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 190, 360, 510);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/teaser_desktop_background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, -100, 1810, 1160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtackSlimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtackSlimeMousePressed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=20 + (Math.random()*1000)%5;

    }//GEN-LAST:event_AtackSlimeMousePressed

    private void AtackSlimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtackSlimeActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_AtackSlimeActionPerformed

    private void attackCaballeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attackCaballeroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_attackCaballeroMousePressed

    private void AttackDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackDActionPerformed
        // TODO add your handling code here:
          BarravidaSlime.setValue(int_vidaslime);
        int_vidaslime -=100 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackDActionPerformed

    private void attackCaballeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackCaballeroActionPerformed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=50 + (Math.random()*1000)%5;
    }//GEN-LAST:event_attackCaballeroActionPerformed

    private void CurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurarMousePressed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=50 + (Math.random()*1000)%5;
    }//GEN-LAST:event_CurarMousePressed

    private void AtaquecargadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtaquecargadoMousePressed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=50+(Math.random()*1000)%5;
    }//GEN-LAST:event_AtaquecargadoMousePressed

    private void AtaquecargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaquecargadoActionPerformed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=50 + (Math.random()*1000)%5;
        
    }//GEN-LAST:event_AtaquecargadoActionPerformed

    private void AtaqueGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtaqueGMousePressed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr -=50 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AtaqueGMousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:       
    }//GEN-LAST:event_jButton2MousePressed

    private void CurardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurardMousePressed
        // TODO add your handling code here:
        Barravidad.setValue(int_vidadr);
        int_vidadr +=5000;
    }//GEN-LAST:event_CurardMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtackSlime;
    private javax.swing.JButton AtaqueG;
    private javax.swing.JButton Ataquecargado;
    private javax.swing.JButton AttackD;
    private javax.swing.JProgressBar BarravidaSlime;
    private javax.swing.JProgressBar Barravidad;
    private javax.swing.JButton Curar;
    private javax.swing.JButton Curard;
    private javax.swing.JButton attackCaballero;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar vidacaballero;
    // End of variables declaration//GEN-END:variables
}
